name: Create Orphan Branch

on:
  workflow_dispatch:
  push:
    branches:
      - master  # Change this to your default branch if it's not 'main'

jobs:
  create-orphan-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Create orphan branch
        run: |
          # Set Git user details
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          # Create an orphan branch named 'builds'
          git checkout --orphan builds
          
          # Remove all files from the index
          git rm -rf .

          # Commit the changes (no files to commit)
          git commit --allow-empty -m "Initial commit on orphan branch 'builds'"

          # Push the orphan branch to the remote repository
          git push origin builds
